### ISSUE TITLE
Adding default texture scale to game config through godot

### ISSUE THREAD

**Issue by PaperMartin** [QodotPlugin/qodot-plugin#120]
Currently, it's possible in trenchbroom to add a default texture scale to the game config file with the scale faceattribs
As far as I know, there's no way to set this attribute in qodot, so the only way to set it is to modify the config file manually after every export, which isn't great
would be nice to have an option to set that in qodot, especially for me since I use 2048x2048 textures and they're huge in trenchbroom by default

**Comment by PaperMartin** [comment]
an example of my config edited to have a default scale on brush UVs of 0.5,0.5 https://hatebin.com/wmhvojwvfv

**Comment by Zaraka** [comment]
+1
