### ISSUE TITLE
I should launch Godot as root to see Qodot nodes, strange no ?

### ISSUE THREAD

**Issue by nuxlight** [QodotPlugin/qodot-plugin#127]
Hi Qodot community :)

I have a strange behavior on my Fedora...
I have installed all requirement to launch Qodot and Trenchbroom on my system but after launch the scripts :
- qodot_trenchbroom_config_file.tres
- qodot_trenchbroom_config_folder.tres
I correctly generate my Trenchbroom configurations but if I am not root I can't see the Qodot nodes :/
 
as user : 
![image](https://user-images.githubusercontent.com/2751135/115446995-42e2b280-a218-11eb-991a-8f78b8fbbbe6.png)

as root : 
![image](https://user-images.githubusercontent.com/2751135/115447193-7ae9f580-a218-11eb-8e09-26484305f3ab.png)

Have you an idea with this problem, it's only a permission problem ?
Thanks for your help :)

**Comment by nuxlight** [comment]
I have launch Godot in verbose in root and user mode I see no specific difference :/

**Comment by Shfty** [comment]
@nuxlight How did you install Qodot?

My first suspicion is that the GDNative libraries (`libmap.so` and `libqodot.so` for linux) have somehow ended up with root ownership or some other restrictive permissions, thus preventing the editor from reading and loading them unless it's running with root permissions.

**Comment by nuxlight** [comment]
@Shfty I have installed Qodot with the zip archive directly (The Godot Asset store API is down at this time) :)

**Comment by nuxlight** [comment]
I have change all permissions (Godot executable and all folder/files presents in project folder) --> Same result, no nodes are presents in normal user :'(

**Comment by PaperMartin** [comment]
Did you activate the plugin in the plugin window?

**Comment by nuxlight** [comment]
@PaperMartin Yes I did that but no effect on nodes explorer.
I have tested on another Linux distribution (On Ubuntu) and you have exactly the same behavior :/

**Comment by RisingThumb** [comment]
@nuxlight 
> @Shfty I have installed Qodot with the zip archive directly (The Godot Asset store API is down at this time) :)

Installing by Zip, doesn't preserve read, write or execute permissions on the files. tar.gz does preserve read/write/execute permissions on the files. Use the .tar.gz to install OR give the files read and write permissions after unzipping it.

If you run this command `chmod -R +wr addons` to give read and write permissions for the addons folder, you should be able to see it without running Godot as root. What this does, is recursively give read and write permissions to all files and folders in the addons folder. If execute permissions are needed(I don't know if they are) change the command to `chmod -R +wrx addons`.

**Comment by Calinou** [comment]
This may be related to SELinux. Try setting it to permissive mode using `sudo setenforce 0` then restart the editor.

**Comment by Calinou** [comment]
@nuxlight Did you find a solution to this problem? If so, please document it here by commenting :slightly_smiling_face:
