### ISSUE TITLE
Qodot does not look for/import bitmap textures

### ISSUE THREAD

**Issue by brookeburkett** [QodotPlugin/qodot-plugin#150]
### What
When importing a .map using Qodot, no bitmap textures are found or applied. 
### How
Create a bitmap texture in the res://textures folder. Create a new trenchbroom map using the provided Qodot .cfg file, properly pointed to the project directory. Texture the default brush with the bitmap texture, then save. Import as a QodotMap node. No texture.

Convert this texture to png, and follow the same steps above. No issue finding the texture and applying it upon import.
### Expected
I would expected a 1:1 from the textures I see in the .map editor in Godot (via. Qodot.) I suspect this may be a limitation on Godot's part, so if that is the case some documentation on this limitation would save others the time i invested in this.

**Comment by puzzud** [comment]
Looks like it's an issue with TGA as well.
