### ISSUE TITLE
Document loading maps at runtime from game resources

### ISSUE THREAD

**Issue by ceceayo** [QodotPlugin/qodot-plugin#159]
Is it possible to load a map from game resources at runtime?

**Comment by Derpford** [comment]
Seconding this--I want to load different maps into the same scene, so that I can have one scene for game logic and load maps in and out of it (I'm making a multiplayer game).

**Comment by DeerTears** [comment]
You can already load maps and build them at runtime by accessing a QodotMap's `map_file` property, and calling `verify_parameters()` then `build_map()`. But I remember people running into dependency errors with their build settings, so I'm hoping someday I can write out the full method for this (including build settings) and add it to https://qodotplugin.github.io/

Maybe it's a bit late, but a suggestion for @Derpford you can always save your complete QodotMap builds as .tscn scenes, and just load that. It's likely faster to load Godot's own data structures from your hard drive than it is to perform the entire build process in QodotMap.

**Comment by DeerTears** [comment]
Moving this to the documentation repo
