### ISSUE TITLE
Unable to load Qodot in Godot Beta 16

### ISSUE THREAD

**Issue by nullsquid** [QodotPlugin/qodot-plugin#163]
latest Qodot release won't load in Gv4.0.beta16.mono.official [518b9e580]. OS is windows 10 64 bit. Attached is console log output of errors

![qodot_errors](https://user-images.githubusercontent.com/6439547/217164536-1b6f08f2-7097-4cf9-aba6-fc0ea0c8d343.jpg)

**Comment by STUDIOEMBYR** [comment]
You've filed this bug in the 3.x plugin repo.

Here is the link to 4.0 support: https://github.com/QodotPlugin/Qodot

**Comment by nullsquid** [comment]
Whoops thank you--it was late and I was tired.
