### ISSUE TITLE
qodot_trenchbroom_config_folder.tres doesn't open (new projects contain icon.svg, not icon.png)

### ISSUE THREAD

**Issue by trollusk** [QodotPlugin/qodot-plugin#170]
It seems in Godot 4, the default icon file for new projects is called icon.svg, not icon.png. This causes Godot to be unable to load qodot_trenchbroom_config_folder.tres, since it has an explicit dependency on icon.png.

**Comment by DeerTears** [comment]
Thanks, I fixed this recently over here: https://github.com/QodotPlugin/Qodot/pull/27
