### ISSUE TITLE
Wiki Documentation

### ISSUE THREAD

**Issue by Shfty** [QodotPlugin/qodot-plugin#62]
This task is for noting any missing wiki documentation that needs to be rectified.

Be sure to check the [wiki](https://github.com/Shfty/qodot-plugin/wiki) before making a request for documentation.

**Comment by Shfty** [comment]
**Qodot Functionality**
- `_phong` property
- `_shadow` property
- Specifics of custom entity spawning
  - How to plug your own top-level class in via PackedScene
- TrenchBroom setup
  - Pointing TB at your game project
  - Loose file / WAD file restructions per format

**Radiant Workflow**
- Radiant is rigid in terms of its game definitions, so need to lean on Q3 + mod config
- Tested with GTKRadiant
- Use the Q3 + mods config, choose the parent directory of your Godot project as the base dir
- Use your project folder's name as the mod name
- Radiant will create a `baseq3` folder next to your project folder
- Delete everything inside `baseq3` except for `scripts/default_project.proj` and `scripts/user0.proj` and `entities.def`
- Recommended to enable 'fixed texture size' in Radiant settings if working with 4K textures
  - Prevents texture window layout blowout
- Need to look into `entities.def` and see about subbing in a basic Qodot equivalent

**Comment by fossegutten** [comment]
Trenchbroom crashes if entity classname has spaces. Might want to add that to entities wiki, either that or trim away spaces on fgd file export?

"Could not load builtin entity definition file 'Qodot.fgd': At line 41, column 68: Expected '[' or ':', but got word (raw data: 'collider')"

**Comment by Shfty** [comment]
Need to document new Quick Build functionality:
```
- there's now a build_complete(entity_nodes) signal that gets fired at the end of the build and returns an array of entity nodes (order corresponds to map file entity order, entities may be null depending on the build process)
- the enum passed into set_owner can now take the following values:
  - QodotMap.QodotMapAction.SELECT_AN_ACTION - Does nothing, used for UI purposes.
  - QodotMap.QodotMapAction.QUICK_BUILD - Build, but don't attach to the editor tree. Visible in the editor, but entity nodes can't be selected or saved. Doesn't invoke costly set_owner calls.
  - QodotMap.QodotMapAction.FULL_BUILD - Original build + add to editor tree behavior.
  - QodotMap.QodotMapAction.UNWRAP_UV2 - Unwrap UV2s for lightmapping. Should work for both quick and full builds.
```

As well as `manual_build()`:
```
- there's a new manual_build() function in QodotMap that also skips the step of attaching entity nodes to the QodotMap itself
- the Use TrenchBroom Group Hierarchy setting doesn't do anything when using manual_build(), since it skips out the attachment phase
```

**Comment by Shfty** [comment]
Need to document signal/slot wiring as per https://github.com/Shfty/qodot-plugin/issues/80

**Comment by Shfty** [comment]
Need to elaborate on install process + plugin activation.

**Comment by Calinou** [comment]
Could you make the wiki editable for non-collaborators as well? This would make it possible for anyone to fix issues like https://github.com/Shfty/qodot-plugin/issues/103 :slightly_smiling_face: 

You can do this in the repository's Settings tab.

**Comment by Shfty** [comment]
@Calinou Good call, it should be opened up for public edits now.

**Comment by DeerTears** [comment]
I just pushed changes to the Usage and Trenchbroom pages to include tutorials on the set-up process for getting the two synced-up. I know you two already proofread what I wrote but I'd greatly appreciate changes from anyone to improve what I wrote!

**Comment by dsvoid** [comment]
I'm having trouble figuring out just how important this really is, but it might be of use to _someone_: in Quake, the player's base is 32 x 32 units and the player's height is 56 units. I noticed in builds of maps that 1 unit in Godot is 32 units in Quake. This means that if you want to make a character the same size, make them about 1 x 1 units at their base and 1.75 units in height.

**Comment by DeerTears** [comment]
Please file new issues at https://github.com/QodotPlugin/qodotplugin.github.io , this repo's wiki is now closed.
